version: "3.8"

services:
  app1:
    build: 
      context: .
      dockerfile: dockerfile
      container_name: app1
      ports:
        - "6081:6080"


  app2:
     build: 
      context: .
      dockerfile: dockerfile
      container_name: app2
      ports:
        - "6082:6080"
   

  app3:
     build: 
      context: .
      dockerfile: dockerfile
      container_name: app3
      ports:
        - "6083:6080"
   

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3